language: ruby
script: bundle exec rake
services: mongodb
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ree
  - ruby-head
gemfile:
 - Gemfile.activerecord3
 - Gemfile.activerecord4
matrix:
  allow_failures:
    - rvm: ruby-head